# Generated by Django 4.2.28 on 2026-03-06 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('placas', models.CharField(max_length=10, unique=True)),
                ('serievin', models.CharField(db_column='serieVIN', max_length=17, unique=True)),
            ],
            options={
                'db_table': 'autobus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('registro', models.IntegerField(primary_key=True, serialize=False)),
                ('connombre', models.CharField(db_column='conNombre', max_length=30)),
                ('conprimerapell', models.CharField(db_column='conPrimerApell', max_length=30)),
                ('consegundoapell', models.CharField(blank=True, db_column='conSegundoApell', max_length=30, null=True)),
                ('licnumero', models.CharField(db_column='licNumero', max_length=15)),
                ('licvencimiento', models.DateField(db_column='licVencimiento')),
                ('fechacontrato', models.DateField(db_column='fechaContrato')),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoViaje',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'edo_viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('numasientos', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fechapago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('panombre', models.CharField(db_column='paNombre', max_length=30)),
                ('paprimerapell', models.CharField(db_column='paPrimerApell', max_length=30)),
                ('pasegundoapell', models.CharField(blank=True, db_column='paSegundoApell', max_length=30, null=True)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pasajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('duracion', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taquillero',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('taqnombre', models.CharField(db_column='taqNombre', max_length=30)),
                ('taqprimerapell', models.CharField(db_column='taqPrimerApell', max_length=30)),
                ('taqsegundoapell', models.CharField(blank=True, db_column='taqSegundoApell', max_length=30, null=True)),
                ('fechacontrato', models.DateField(db_column='fechaContrato')),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('supervisa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taquillero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('dircalle', models.CharField(db_column='dirCalle', max_length=30)),
                ('dirnumero', models.CharField(db_column='dirNumero', max_length=10)),
                ('dircolonia', models.CharField(db_column='dirColonia', max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'terminal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaemision', models.DateTimeField(db_column='fechaEmision')),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAsiento',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPasajero',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('descuento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_pasajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fechorasalida', models.DateTimeField(db_column='fecHoraSalida')),
                ('fechoraentrada', models.DateTimeField(db_column='fecHoraEntrada')),
            ],
            options={
                'db_table': 'viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViajeAsiento',
            fields=[
                ('asiento', models.OneToOneField(db_column='asiento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='taquilla.asiento')),
                ('ocupado', models.IntegerField()),
            ],
            options={
                'db_table': 'viaje_asiento',
                'managed': False,
            },
        ),
    ]
