# Generated by Django 4.2 on 2026-03-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taquilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPasajero',
            fields=[
                ('pasajero_num', models.OneToOneField(db_column='pasajero_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='taquilla.pasajero')),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('proveedor', models.CharField(default='local', max_length=50)),
                ('foto', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cuenta_pasajero',
                'managed': False,
            },
        ),
    ]
