// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtKUAiFwFXFFZpB_8G8jDrhh172Q0eYHs',
    appId: '1:49101984438:web:8d09b64f287b3949124c17',
    messagingSenderId: '49101984438',
    projectId: 'rbeusers',
    authDomain: 'rbeusers.firebaseapp.com',
    storageBucket: 'rbeusers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJOvoMcCW2jtO8XdmSLGK4nOJwpYeKeA',
    appId: '1:49101984438:android:b0f3f70f30d122df124c17',
    messagingSenderId: '49101984438',
    projectId: 'rbeusers',
    storageBucket: 'rbeusers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLQV_INUOlSCGSGwzGIxt9RGpKfPcJywU',
    appId: '1:49101984438:ios:80b8decdbdfc635c124c17',
    messagingSenderId: '49101984438',
    projectId: 'rbeusers',
    storageBucket: 'rbeusers.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLQV_INUOlSCGSGwzGIxt9RGpKfPcJywU',
    appId: '1:49101984438:ios:80b8decdbdfc635c124c17',
    messagingSenderId: '49101984438',
    projectId: 'rbeusers',
    storageBucket: 'rbeusers.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtKUAiFwFXFFZpB_8G8jDrhh172Q0eYHs',
    appId: '1:49101984438:web:c5e3606f71f41a11124c17',
    messagingSenderId: '49101984438',
    projectId: 'rbeusers',
    authDomain: 'rbeusers.firebaseapp.com',
    storageBucket: 'rbeusers.firebasestorage.app',
  );

}